SELECT * FROM FASTLOG; 

SELECT * FROM AVERAGED;

SELECT * FROM PALETTE;

SELECT * FROM PREFERENCE;

SELECT * FROM STAT;

SELECT * FROM STATE;

SELECT * FROM TRIPINFO;

SELECT * FROM TRIPS;

fastlog_Index(['TIMESTAMP', 'RPS', 'ODO', 'SPEED_OBD', 'GPS_LAT', 'GPS_LON',
       'GPS_SPEED', 'GPS_ALT', 'HV_V', 'HV_A', 'SOC', 'ICE_TEMP', 'ICE_RPM',
       'ICE_PWR', 'BRK_REG_TRQ', 'BRK_MCYL_TRQ', 'TRIP_NBS', 'TRIP_EV_NBS',
       'TRIP_MOV_NBS', 'TRIP_DIST', 'TRIP_EV_DIST', 'HSI', 'MG2_RPM', 'IGN',
       'LTFT', 'STFT', 'TRIPFUEL', 'FUELFLOWH', 'DCL', 'CCL', 'BSFC',
       'ICE_LOAD', 'INVERTER_TEMP', 'BATTERY_TEMP', 'MG_TEMP', 'INHALING_TEMP',
       'AMBIENT_TEMP', 'ROOM_TEMP', 'MG2_TORQUE', 'MG1_RPM', 'MG1_TORQUE',
       'MGR_RPM', 'MGR_TORQUE', 'GLIDEINDEX', 'ACCELERATOR', 'POSITIVEKWH',
       'NEGATIVEKWH'],
      dtype='object')

tripinfo_Index(['TIMESTAMP', 'CARMODEL', 'VIN', 'VERSIONCODE', 'NUMSAMPLES',
       'CONNECTIONMODE', 'MAC', 'NAME', 'MANUFACTURER', 'KWHPOS', 'KWHNEG',
       'ICE_KWH', 'EXCESSIVE_EV', 'NUMBRAKES', 'NUMBADBRAKES', 'NUMHALFBRAKES',
       'REGENKWH', 'ACCELRATING', 'IGN', 'INEFFIGN', 'SOCGAINBRAKING',
       'SOCGAINCOASTING', 'SOCGAINICE', 'FIRMWARE', 'DISCONNECTIONS',
       'CorruptedFrames', 'TotalFrames', 'GlideType'],
      dtype='object')